tutorial:
  outputs:
    dev:
      account: ka60492.west-europe.azure
      database: analytics
      password: Password123
      role: transform_role
      schema: dbt
      threads: 1
      type: snowflake
      user: TRANSFORM_USER
      warehouse: TRANSFORM_WH
      client_session_keep_alive: False
  target: dev
